version: "3.9"

services:
  web:
    image: php-apache-mysql:8.0-xdebug3.0
    container_name: servidor-web
    ports:
      # El puerto predefinido es el 80, pero en mi host doméstico se modifica al 81 por problemas de permisos
      - 81:80
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    volumes:
      - ./webapp:/var/www/html
    depends_on:
      - db
    networks:
      - default
      
  db:
    image: 'mysql'
    container_name: servidor-mysql
    ports: 
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: gestor
      MYSQL_DATABASE: vacunacionCovid
      MYSQL_USER: gestor
      MYSQL_PASSWORD: gestor
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    networks:
      - default

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
      - web
    networks:
      - default

networks:
  default:

volumes:
  webapp:
  db-data: